name: "FrenchStream"
description: "Addon Stremio pour FrenchStream - Films et SÃ©ries en streaming"
version: "1.8.1"
slug: "frenchstream"
url: "https://github.com/djodjo02130/frenchstream"
init: false
arch:
  - amd64
  - aarch64
  - armv7
ports:
  7000/tcp: 7000
ports_description:
  7000/tcp: "Stremio addon HTTP"
map:
  - config:rw
options:
  tmdb_api_key: ""
schema:
  tmdb_api_key: "str?"
startup: "application"
boot: "auto"
