name: "FrenchStream"
description: "Addon Stremio pour FrenchStream - Films et SÃ©ries en streaming"
version: "1.2.3"
slug: "frenchstream"
url: "https://github.com/djodjo02130/frenchstream"
init: false
arch:
  - amd64
  - aarch64
  - armv7
ports:
  7000/tcp: 7000
ports_description:
  7000/tcp: "Stremio addon HTTP"
map:
  - config:rw
options: {}
schema: {}
startup: "application"
boot: "auto"
